language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="bef54a20-a5a5-4895-b124-599659f2e9d3"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -sodnopov@list.ru
    on_success: never # default: change
    on_failure: always # default: always